### ISSUE TITLE
Viewing stats errors out

### ISSUE THREAD

**Issue by dend** [Netflix/osstracker#49]
Whenever I am trying to read in the information from OSS Tracker, it seems like it errors out:

<img width="1262" alt="screen shot 2018-04-05 at 8 34 05 pm" src="https://user-images.githubusercontent.com/1389609/38402419-f78355a6-3910-11e8-9c02-dd6d319ee59c.png">

This is what I get in the console:

<img width="868" alt="screen shot 2018-04-05 at 8 37 58 pm" src="https://user-images.githubusercontent.com/1389609/38402463-440f4e66-3911-11e8-96a4-1d678b26e4c2.png">

**Comment by mattseaborn** [comment]
When you the docker logs you will likely find that you see

`error = Error: connect ECONNREFUSED 127.0.0.1:9200`

The documentation appears to be in error,  you need to link the console container to the cassandra and elk containers

`docker run -d --name osstracker-console --link osstracker-elasticsearch:elasticsearch --link osstracker-cassandra:cassandra -e CASS_HOST=cassandra -e CASS_PORT=${CASS_PORT} -e ES_HOST=elasticsearch -e ES_PORT=${ES_PORT} -p 3000:3000 netflixoss/osstracker-console`
