### ISSUE TITLE
Create a docker deployment of the technology

### ISSUE THREAD

**Issue by aspyker** [Netflix/osstracker#6]
We are already running both the scraper and console in containers at Netflix.  It would be a days worth of worth to get these containers ready for a version that could be used for testing and demos.  We would need to make sure that the elastic search and cassandra dockerhub official containers worked as expected as we do not run those services on containers today.  If we made these docker images, it would be good to publish them to dockerhub as well to make it easier to run osstracker before learning to build it.

**Comment by ralfschimmel** [comment]
Yeah, docker-compose with public containers would be awesome!

**Comment by aspyker** [comment]
Added docker compose setup.  Will need to add a few more things, but seems functional as is.

**Comment by evaldasou** [comment]
It's not functional by default. To expose github token as per docker-compose documentation is not enough.
Is this the end of this project?
