### ISSUE TITLE
Installation failed because of CASS_HOST property

### ISSUE THREAD

**Issue by javiereguiluz** [Netflix/osstracker#9]
FAILURE: Build failed with an exception.

* Where:
Build file 'osstracker/osstracker-scraper/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':osstracker-scraper'.
Could not find property 'CASS_HOST' on task ':osstracker-scraper:runScraper'.

**Comment by kakawait** [comment]
You should specify your _Cassandra_ host/port and _ES_ host port like following

By your own configuration, here my sample using _Cassandra_ and _ES_ official docker container on `localhost`

```
./gradlew -PCASS_HOST=localhost -PCASS_PORT=9042 -PES_HOST=localhost -PES_PORT=9200 -Pgithub_oauth=XXXXXXX
```

But you should change `XXXXXXX` by our generated key (using _GitHub Personal Settings_ -> _Personal access tokens_)

--- 

Until #6 manual installation is necessary, is not so hard using _Cassandra_/_ES_ container. Don't forget to generate DDL before starting https://github.com/Netflix/osstracker/tree/master/osstracker-ddl

Create _Cassandra_ and _ES_ container

```
docker run --name cassandra -d -p 9042:9042 cassandra
docker run --name elasticsearch -d -p 9200:9200 -p 9300:9300 elasticsearch
```

Connect to _Cassandra_ from cqlsh

```
docker run -it --link cassandra:cassandra --rm cassandra cqlsh cassandra
```

Then run command on https://github.com/Netflix/osstracker/blob/master/osstracker-ddl/osstracker.cql, in my use case I replace

```
CREATE KEYSPACE osstracker WITH replication = {
  'class': 'NetworkTopologyStrategy',
  'us-east': '3'
};
```

by 

```
CREATE KEYSPACE osstracker WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 };
```

Create _ES_ index using instruction here https://github.com/Netflix/osstracker/blob/master/osstracker-ddl/elasticsearch.txt

**Comment by javiereguiluz** [comment]
@kakawait thanks for your quick response. Closing it as duplicated of #7.
